#! Need to change YOUR_CLUSTER and YOUR_API_TOKEN accordingly
#@ load("@ytt:data", "data")
---
apiVersion: v1
stringData:
  password: #@ data.values.wavefrontToken
kind: Secret
metadata:
  name: wavefront-token
  namespace: #@ data.values.workloadNamespace
---
apiVersion: v1
stringData:
  uri: #@ data.values.wavefrontURI
kind: Secret
metadata:
  name: wavefront-uri
  namespace: #@ data.values.workloadNamespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wavefront-proxy
    name: wavefront-proxy
  name: wavefront-proxy
  namespace:  #@ data.values.workloadNamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      containers:
      - name: wavefront-proxy
        image: wavefronthq/proxy:latest
        imagePullPolicy: Always
        env:
        - name: WAVEFRONT_URL
          valueFrom:
            secretKeyRef:
              name: wavefront-uri
              key: uri
        - name: WAVEFRONT_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront-token
              key: password
        #! Zipkin Tracing Environment Variable
        - name: WAVEFRONT_PROXY_ARGS
          value: --traceJaegerGrpcListenerPorts 30001 --traceJaegerApplicationName acme-fitness-demo
          #! value: --traceZipkinListenerPorts 9411 --traceZipkinApplicationName acme-fitness-demo 
        ports:
        - containerPort: 2878
          protocol: TCP
        #! Zipkin Tracing Port
        #! - containerPort: 9411
        #!   protocol: TCP
        - containerPort: 30001
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  labels:
    app: wavefront-proxy
  namespace:  #@ data.values.workloadNamespace
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
    targetPort: 2878
  #! Added for Yaeger Tracing
  - name: yaeger
    port: 30001
    targetPort: 30001
    protocol: TCP
  #! Added for Zipkin Tracing
  #! - name: zipkin
  #!   port: 9411
  #!   targetPort: 9411
  #!   protocol: TCP
  selector:
    app: wavefront-proxy
